### PR TITLE
readme update & fix for Postgres columns retrieve process

### PR DESCRIPTION
**Pull request by danysz**
…p from sources.

### CODE REVIEW

**Comment by danysz** [comment]
When do you think you will be able to release a new version ?
I really prefer to work with the "binary" and not with the custom made by me.

Thanks

**Comment by smallnest** [comment]
v0.9.29 released. thanks for your fix.

**Comment by swarupdonepudi** [comment]
I dont get the latest version when i run `go get -u github.com/smallnest/gen` i still get the v27. Should release the tag?

**Comment by swarupdonepudi** [comment]
ok even though the version is v27, it works. so i think the version number needs to be updated in the latest release.

**Pull request merged**
